#:kivy 2.1.0

MDScreen:
    name:'splashscreen'
    MDFloatLayout:
        Image:
            source: "logo_a.gif"
            pos_hint: {"center_x": 0.5, 'center_y': 0.6}
            padding_y: 10
            size_hint: 0.8,0.8
        
        MDLabel:
            text: "Loading... Please Wait!"
            pos_hint:{"center_x": 0.5, 'center_y': 0.4}
            halign: 'center'
            font_style: 'Subtitle1'


       