#:kivy 2.1.0
<MDLabel>:
    halign:'center'
MDScreen:
    name:"user_screen"
    address:address
    balance:balance
    internet_speed:internet_speed
    user_name:user_name
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            id:user_name
            title: ""

        MDLabel:
            id:address
            text: ""

        MDLabel:
            id:balance
            text: ""

        MDLabel:
            id:internet_speed
            text: ""